# Generated by Django 5.2.14 on 2026-05-24 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('extra', 'Extra')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to='recipes.recipe')),
            ],
            options={
                'ordering': ['date', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date', 'meal_type', 'recipe'), name='unique_recipe_once_per_owner_slot')],
            },
        ),
    ]
