# Generated by Django 5.2.14 on 2026-05-31 16:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cooked', 'Cooked'), ('skipped', 'Skipped'), ('postponed', 'Postponed')], max_length=16)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planned_meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to='planning.plannedmeal')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PantryConsumptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('unit', 'unit')], default='unit', max_length=8)),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planning.mealconsumption')),
            ],
            options={
                'ordering': ['name', 'unit'],
            },
        ),
    ]
