# Generated by Django 5.2.14 on 2026-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomponent',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='store',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
