# Generated by Django 5.2.14 on 2026-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingitem_brand_shoppingitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='store',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
