# Generated by Django 5.2.14 on 2026-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shoppingitem_brand_alter_shoppingitem_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='store',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
