# Generated by Django 5.2.14 on 2026-05-26 18:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_shoppingitem_brand_alter_shoppingitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='pantry_synced_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='pantry_synced_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='pantry_synced_unit',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
